inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "lib/**/*"
    - "log/**/*"
    - 'tmp/**/*'
    - "vendor/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "Gemfile"

#################### Bundler ####################

# without

#################### Gemspec ####################

# without

#################### Layout ####################

Layout:
  Enabled: false

#################### Lint ####################

# without

#################### Metrics ####################

Metrics:
  Enabled: false

#################### Migration ####################

# without

#################### Naming ####################

# without

#################### Security ####################

# without

#################### Style ####################

Style:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

#################### Performance ####################

# without

#################### Rails ####################

Rails:
  Enabled: false

#################### RSpec ####################

RSpec:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: true
  Exclude:
    - 'spec/system/categories_management_flow_spec.rb'
    - 'spec/system/comments_management_flow_spec.rb'
    # - 'spec/system/header_click_events_spec.rb'
    - 'spec/system/links_button_flow_spec.rb'
    - 'spec/system/login_user_select_spec.rb'
    - 'spec/system/makers_management_flow_spec.rb'
    - 'spec/system/picture_size_spec.rb'
    - 'spec/system/samples_management_flow_spec.rb'
    # - 'spec/system/samples_search_flow_spec.rb'
    - 'spec/system/user_login_spec.rb'
    - 'spec/system/user_logout_flow_spec.rb'
    - 'spec/system/users_management_flow_spec.rb'

RSpec/EmptyLineAfterHook:
  Enabled: true
  Exclude:
    - 'spec/system/categories_management_flow_spec.rb'
    - 'spec/system/comments_management_flow_spec.rb'
    # - 'spec/system/header_click_events_spec.rb'
    - 'spec/system/links_button_flow_spec.rb'
    - 'spec/system/login_user_select_spec.rb'
    - 'spec/system/makers_management_flow_spec.rb'
    - 'spec/system/picture_size_spec.rb'
    - 'spec/system/samples_management_flow_spec.rb'
    # - 'spec/system/samples_search_flow_spec.rb'
    - 'spec/system/user_login_spec.rb'
    - 'spec/system/user_logout_flow_spec.rb'
    - 'spec/system/users_management_flow_spec.rb'

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true
  Exclude:
    - 'spec/system/categories_management_flow_spec.rb'
    - 'spec/system/comments_management_flow_spec.rb'
    # - 'spec/system/header_click_events_spec.rb'
    - 'spec/system/links_button_flow_spec.rb'
    - 'spec/system/login_user_select_spec.rb'
    - 'spec/system/makers_management_flow_spec.rb'
    - 'spec/system/picture_size_spec.rb'
    - 'spec/system/samples_management_flow_spec.rb'
    # - 'spec/system/samples_search_flow_spec.rb'
    - 'spec/system/user_login_spec.rb'
    - 'spec/system/user_logout_flow_spec.rb'
    - 'spec/system/users_management_flow_spec.rb'
