inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false


#################### Bundler ####################

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

#################### Gemspec ####################

# without

#################### Layout ####################

Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - 'Gemfile'
    - 'config/initializers/assets.rb'

Layout/TrailingEmptyLines:
  Exclude:
    - 'spec/hello_spec.rb'

Layout/LineLength:
  Max: 198

Layout/IndentationWidth:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/models/**/*'
    - 'app/uploaders/**/*'

Layout/IndentationConsistency:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/models/**/*'
    - 'app/uploaders/**/*'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'app/controllers/**/*'
    - 'db/**/*'
    - 'spec/**/*'

Layout/IndentationStyle:
  Exclude:
    - 'app/uploaders/**/*'

Layout/LeadingCommentSpace:
  Exclude:
    - 'spec/**/*'

Layout/SpaceBeforeComment:
  Exclude:
    - 'spec/**/*'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/SpaceInLambdaLiteral:
  Exclude:
    - 'app/models/**/*'

Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*'

#################### Lint ####################

Lint/RedundantCopDisableDirective:
  Exclude:
    - 'spec/**/*'

#################### Metrics ####################

Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/**/*'
    - 'db/**/*'

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 13

Metrics/PerceivedComplexity:
  Max: 9

Metrics/AbcSize:
  Exclude:
    - 'app/uploaders/**/*'

#################### Migration ####################

# without

#################### Naming ####################

# without

#################### Security ####################

# without

#################### Style ####################

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/*'
    - 'app/helpers/*'
    - 'app/mailers/**/*'
    - 'app/models/*'
    - 'config/application.rb'
    - 'db/**/*'
    - 'app/uploaders/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'
    - 'app/models/**/*'
    - 'spec/**/*'
    - 'app/helpers/**/*'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/application.rb'
    - 'config/initializers/assets.rb'
    - 'app/uploaders/**/*'

Style/PerlBackrefs:
  Exclude:
    - 'bin/bundle'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10

Style/NumericLiterals:
  Exclude:
    - 'db/**/*'

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/WordArray:
  Exclude:
    - 'db/**/*'
    - 'spec/helpers/*'

Style/HashSyntax:
  Exclude:
    - 'db/**/*'
    - 'app/models/**/*'

Style/GuardClause:
  Exclude:
    - 'app/models/**/*'
    - 'app/helpers/**/*'
    - 'app/controllers/**/*'

Style/MutableConstant:
  Exclude:
    - 'db/**/*'

Style/RedundantInterpolation:
  Exclude:
    - 'app/models/**/*'

Style/Lambda:
  Exclude:
    - 'app/models/**/*'

Style/SafeNavigation:
  Exclude:
    - 'app/controllers/*'

Style/SymbolProc:
  Exclude:
    - 'app/helpers/*'

Style/RegexpLiteral:
  Exclude:
    - 'app/models/**/*'

Style/SoleNestedConditional:
  Exclude:
    - 'app/models/**/*'
