inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "log/**/*"
    - 'tmp/**/*'
    - "vendor/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "Gemfile"

#################### Bundler ####################

# without

#################### Gemspec ####################

# without

#################### Layout ####################

Layout:
  Enabled: false

#################### Lint ####################

# without

#################### Metrics ####################

# without

#################### Migration ####################

# without

#################### Naming ####################

# without

#################### Security ####################

# without

#################### Style ####################

Style:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

#################### Performance ####################

# without

#################### Rails ####################

Rails:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/Validation:
  Enabled: true

Rails/FindByOrAssignmentMemoization:
  Enabled: true

Rails/OrderArguments:
  Enabled: true

#################### RSpec ####################

RSpec:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/ExpectInHook:
  Enabled: true

RSpec/ExampleLength:
  Enabled: true
  Max: 15

RSpec/HookArgument:
  Enabled: true

RSpec/LetBeforeExamples:
  Enabled: true

#################### FactoryBot ####################

# クラス属性を明示的に設定する際は文字列値を使用する
FactoryBot/FactoryClassName:
  Enabled: false

# モジュール名：FactoryBotの記述を省略する
FactoryBot/SyntaxMethods:
  Enabled: false

# リスト内で作成されるモデルの数を制限する (デフォルト値：10)
FactoryBot/ExcessiveCreateList:
  Enabled: true
