inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "lib/**/*"
    - "log/**/*"
    - 'tmp/**/*'
    - "vendor/**/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "Gemfile"

#################### Bundler ####################

# without

#################### Gemspec ####################

# without

#################### Layout ####################

Layout:
  Enabled: false

#################### Lint ####################

# without

#################### Metrics ####################

# without

#################### Migration ####################

# without

#################### Naming ####################

# without

#################### Security ####################

# without

#################### Style ####################

Style:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

#################### Performance ####################

# without

#################### Rails ####################

Rails:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/Validation:
  Enabled: true

#################### RSpec ####################

RSpec:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/ExpectInHook:
  Enabled: true

RSpec/ExampleLength:
  Enabled: true
  Max: 10

RSpec/HookArgument:
  Enabled: true

RSpec/LetBeforeExamples:
  Enabled: true
