source "https://rubygems.org"

ruby "3.2.6"

gem "rails", "7.2.2"
gem "puma"
gem "jbuilder"
gem "bcrypt"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "faker"
gem 'pg'
gem 'bundler'
gem 'rack-cors'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem 'simplecov', require: false
end

group :development do
  gem "web-console"
  gem "better_errors"
  gem "binding_of_caller"
  gem "rubocop", require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec'
  gem 'bullet'
  gem 'brakeman'
end
