source "https://rubygems.org"

ruby "3.2.6"

gem "rails", "7.2.2"
gem "puma"
gem "jbuilder"
gem "bcrypt"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "faker"
gem 'pg'
gem 'bundler'
gem 'rack-cors'
gem 'will_paginate'
gem "image_processing", ">= 1.2"
gem 'cloudinary'
gem 'jwt'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails", '8.0.2'
  gem "factory_bot_rails"
  gem 'simplecov', require: false
end

group :development do
  gem "web-console"
  gem "better_errors"
  gem "binding_of_caller"
  gem "rubocop", '1.82.1', require: false
  gem 'rubocop-performance', '1.26.1', require: false
  gem 'rubocop-rails', '2.34.3', require: false
  gem 'rubocop-rspec', '3.9.0', require: false
  gem 'bullet'
  gem 'brakeman', '7.1.1'
end
