version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          command: |
            bundle config set path 'vender/bundle' && \
            bundle install
      - save_cache:
          paths:
            - ./vender/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          command: bundle exec rubocop
      - run:
          command: bundle exec rspec

workflows:
  version: 2
  workflow:
    jobs:
      - test