version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.4-browsers
      - image: cimg/postgres:16.1
        environment:
            POSTGRES_USER: example
            POSTGRES_DB: example_dev
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: example
      PGPASSWORD: ""
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"

    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          name: restore gems
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: bundle install
          command: |
            bundle config set path 'vendor/bundle' && \
            bundle install
      - save_cache:
          name: save gems
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          command: bin/rails db:create
      - run:
          command: bundle exec rubocop
      - run:
          command: bundle exec rspec

workflows:
  version: 2
  workflow:
    jobs:
      - test