version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.0
      - image: cimg/postgres:16.1
        environment:
            POSTGRES_USER: example
            POSTGRES_DB: example_dev
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: example
      PGPASSWORD: ""
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"

    steps:
      - checkout
      - run:
          name: Dependency installation
          command: bundle install
      - run:
          name: Database initialization
          command: bin/rails db:create
      - run:
          name: Running rubocop
          command: bundle exec rubocop
      - run:
          name: Setup WebDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y chromium-chromedriver
            sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/
      - run:
          name: Running rspec
          command: bundle exec rspec

workflows:
  version: 2
  workflow:
    jobs:
      - test:
          filters:
            branches:
              only: main