default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # docker compose
  # username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  # password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  # host: <%= ENV['POSTGRES_HOST'] || 'db' %>

development:
  <<: *default
  database: example_dev

test:
  <<: *default
  database: example_sandbox

production:
  <<: *default
  database: example_production
  username: example
  password: <%= ENV["SURFACE_TREATMENT_MANAGER_DATABASE_PASSWORD"] %>