name: Playwright Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend/

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: frontend/

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
